version: '3.7'

services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3007:3007
    stdin_open: true
    environment:
      - PORT=3007
    command: npm start
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - 8080:8080
volumes:
  node_modules:
